---
services:
  rss2socials:
    container_name: rss2socials
    image: toozej/rss2socials:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.rss2socials.rule=Host(`rss2socials.test`)"
      # - "traefik.http.routers.rss2socials.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.rss2socials-secure.entrypoints=https"
      # - "traefik.http.routers.rss2socials-secure.rule=Host(`rss2socials.test`)"
      # - "traefik.http.routers.rss2socials-secure.middlewares=headers@file"
      # - "traefik.http.routers.rss2socials-secure.tls=true"
    # networks:
      # - traefik
